### ISSUE TITLE
Error in Training a Bangla Voice

### ISSUE THREAD

**Issue by arif334** [google/language-resources#17]
Hi,
I was trying to build a Bangla Festival voice according to [this](https://github.com/googlei18n/language-resources/tree/master/bn/festvox) guideline. But I got an error in the training phase. The error messages are quite long, but the first one was this:
`xargs: <path to festival>/build/festvox/src/ehmm/bin/FeatureExtraction: No such file or directory`

Can anyone point out the reasons for this error and/or methods to solve this problem.

Thanks in advance.

**Comment by pasindud** [comment]
It seems like ehmm was not install correctly. 
- Try deleting everything under ```/build/.....```
- Run this script [1]
- Then run the script to install festival again.
   ```
     export FESTIVAL_SUIT_PATH=<your desired path to install Festival>
     mkdir ${FESTIVAL_SUIT_PATH} && ./third_party/festvox/setup.sh 
   ```

1 - https://gist.github.com/pasindud/83428223032ca8ac35d47774fa55e6b8

**Comment by arif334** [comment]
Thanks, @pasindud. I'll do it and post the results back.

**Comment by arif334** [comment]
@pasindud The above problem is solved. I've build a festival voice successfully (using google data). Now I am having an error in setting up merlin. The error goes as follows:
```
Generating HTS questions
Traceback (most recent call last):
  File "./festival_utils/generate_hts_questions.py", line 162, in <module>
    main(sys.argv)
  File "./festival_utils/generate_hts_questions.py", line 121, in main
    phonology = json.loads(open(argv[1]).read())
IOError: [Errno 2] No such file or directory: 'en_US.UTF-8/festvox/phonology.json'

```
It seems that `generate_hts_questions.py` does not getting the path of `phonology.json` file. Should I hard-code the path in the code? Or is there any better way?

**Comment by pasindud** [comment]
Fixed the typo in https://github.com/googlei18n/language-resources/commit/d4b8e64a8dab964b06ff7ba3b92b74ea9f5a3204 , patch the new commit and it should work.

**Comment by mjansche** [comment]
Variable clash with $LANG?

**Comment by pasindud** [comment]
Yea, should be fixed now

**Comment by arif334** [comment]
> It seems like ehmm was not install correctly.
> 
> * Try deleting everything under `/build/.....`
> * Run this script [1]
> * Then run the script to install festival again.
>   ```
>     export FESTIVAL_SUIT_PATH=<your desired path to install Festival>
>     mkdir ${FESTIVAL_SUIT_PATH} && ./third_party/festvox/setup.sh 
>   ```
> 
> 1 - https://gist.github.com/pasindud/83428223032ca8ac35d47774fa55e6b8

@pasindud Problem still exists. I ran your script. Everything was installed successfully, except `realpath` (Is that a problem? If so, what is the work-around?). Then installed festival again. But it seems that probably `festvox` is not installed correctly. There is no entry of 
```<path to festival>/build/festvox/src/ehmm/bin/FeatureExtraction```. 
The size of `festvox` folder is `11.8 MB`. But I remember it's size was around `30 MB` when I installed it with merlin a few months ago (but unfortunately, I deleted that folder). 

Can you have look at it? My python and gcc versions are mentioned below, in case it is required.
```
$ python --version
Python 2.7.15 :: Anaconda, Inc.
$ gcc --version
gcc (Ubuntu 4.8.5-4ubuntu8) 4.8.5
```

**Comment by pasindud** [comment]
> @pasindud The above problem is solved. I've built a festival voice successfully (using google data). 

I assumed previously when you said the above, the ```.../ehmm/bin/FeatureExtraction``` issue was fixed.

**Comment by arif334** [comment]
I fixed that issue by copying `festvox` folder from a previous merlin installation into `festival/build/` directory.  But then I decided, that shouldn't be the proper way to set things up. So, today I removed everything, and started from scratch ... by installing merlin, and so on. But now I notice that `.../ehmm/bin/FeatureExtraction` is missing everywhere. So I can not proceed with festival training anymore. 

The error of installing `realpath` is:
```
$ sudo apt install realpath
[sudo] password for arif: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package realpath is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  manpages-pl manpages-fr-extra

E: Package 'realpath' has no installation candidate
```

**Comment by pasindud** [comment]
Actually both of the festivals installations are similar so you can use the merlin's festival installation if it works.

To fix realpath 
run 

```
sudo apt-get install coreutils
which realpath
``` 
or in [1] replace
```export MERLIN_PATH=$(realpath "$2")``` with ```export MERLIN_PATH=$2``` just make sure you give a absolute path when running setup_merlin.sh.




1 - https://github.com/googlei18n/language-resources/blob/master/festival_utils/setup_merlin.sh#L43

**Comment by pasindud** [comment]
Assuming this is fixed
